# Generated by Django 4.0.2 on 2022-05-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_staff_account_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
