# Generated by Django 4.0.2 on 2022-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_uploaddocument_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200, null=True)),
                ('subject1', models.CharField(max_length=200, null=True)),
                ('subject2', models.CharField(max_length=200, null=True)),
                ('subject3', models.CharField(max_length=200, null=True)),
                ('subject4', models.CharField(max_length=200, null=True)),
                ('subject5', models.CharField(max_length=200, null=True)),
                ('subject6', models.CharField(max_length=200, null=True)),
                ('subject7', models.CharField(max_length=200, null=True)),
                ('subject8', models.CharField(max_length=200, null=True)),
                ('subject9', models.CharField(max_length=200, null=True)),
                ('subject10', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
