# Generated by Django 4.0.2 on 2022-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='level',
            field=models.CharField(choices=[('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('G10', 'Grade 10'), ('G11', 'Grade 11'), ('G12', 'Grade 12')], max_length=200, null=True, unique=True),
        ),
    ]
