# Generated by Django 4.0.2 on 2022-05-19 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='LRN',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
