# Generated by Django 4.0.2 on 2022-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_portal', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
